wandb_version: 1

dataset:
  desc: null
  value: MNIST
algorithm:
  desc: null
  value: BP
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 256
seed:
  desc: null
  value: 1
test:
  desc: null
  value: true
depth:
  desc: null
  value: 6
direct_depth:
  desc: null
  value: 1
in_dim:
  desc: null
  value: 784
hid_dim:
  desc: null
  value: 256
out_dim:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.1
learning_rate_backward:
  desc: null
  value: 0.001
std_backward:
  desc: null
  value: 0.01
stepsize:
  desc: null
  value: 0.01
label_augmentation:
  desc: null
  value: false
forward_function_1:
  desc: null
  value: parameterized
forward_function_2:
  desc: null
  value: parameterized
backward_function_1:
  desc: null
  value: parameterized
backward_function_2:
  desc: null
  value: parameterized
forward_function_1_init:
  desc: null
  value: orthogonal
forward_function_2_init:
  desc: null
  value: orthogonal
backward_function_1_init:
  desc: null
  value: gaussian
backward_function_2_init:
  desc: null
  value: orthogonal
sparse_ratio:
  desc: null
  value: -1
forward_function_1_activation:
  desc: null
  value: linear-BN
forward_function_2_activation:
  desc: null
  value: tanh-BN
backward_function_1_activation:
  desc: null
  value: tanh-BN
backward_function_2_activation:
  desc: null
  value: linear-BN
forward_last_activation:
  desc: null
  value: linear-BN
loss_feedback:
  desc: null
  value: DTP
epochs_backward:
  desc: null
  value: 5
log:
  desc: null
  value: true
agent:
  desc: null
  value: false
continual:
  desc: null
  value: 'no'
save:
  desc: null
  value: 'yes'
activation_function:
  desc: null
  value: tanh-BN
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711124266.917915
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
