wandb_version: 1

ff1:
  desc: null
  value:
    type: parameterized
    init: null
    act: linear-BN
ff2:
  desc: null
  value:
    type: parameterized
    init: parameterized_init
    act: tanh-BN
bf1:
  desc: null
  value:
    type: random
    init: parameterized_init-sparse-0.1
    act: tanh-BN
bf2:
  desc: null
  value:
    type: difference
    init: null
    act: linear-BN
last:
  desc: null
  value: linear-BN
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712951052.469827
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
